version: "2"

services:
  dynamodblocal:
    container_name: dynamo
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    hostname: localhost
    ports:
      - "8000:8000"

  minio:
    container_name: minio
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=ALEXIAFOLEYS7EXAMPLE
      - MINIO_SECRET_KEY=w1asrXU1nFwMI/K7MDGNG/bPxRfyCYEXAMPLEKEY
      - MINIO_REGION_NAME=local
    command: server /data
    hostname: localhost
    ports:
      - "9000:9000"
