version = 0.1

[staging.deploy.parameters]
stack_name = "diamory-server-staging"
resolve_s3 = true
s3_prefix = "diamory-server-staging"
region = "eu-central-1"
profile = "diamory"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Stage='staging', Account='828803652383', HostedZone='Z02112923J7IQK3X4KU7D'"
confirm_changeset = true

[prod.deploy.parameters]
stack_name = "diamory-server-prod"
resolve_s3 = true
s3_prefix = "diamory-server-prod"
region = "eu-central-1"
profile = "diamory"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Stage='prod', Account='828803652383', HostedZone='Z02112923J7IQK3X4KU7D'"
confirm_changeset = true
