version = 0.1

[staging.deploy.parameters]
stack_name = "diamory-server-staging"
resolve_s3 = true
s3_prefix = "diamory-server-staging"
region = "eu-central-1"
profile = "diamory"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Stage=\"staging\""
confirm_changeset = true

[prod.deploy.parameters]
stack_name = "diamory-server-prod"
resolve_s3 = true
s3_prefix = "diamory-server-prod"
region = "eu-central-1"
profile = "diamory"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "Stage=\"prod\""
confirm_changeset = true
